# Generated by Django 4.0.4 on 2022-05-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='A room name', max_length=255)),
                ('gameMode', models.IntegerField(choices=[(0, 'Test')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Yellari the Forbidden One', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Player'), (2, 'Spectator')], default=1)),
                ('playerData', models.JSONField(blank=True, default=dict, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmcro.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmcro.user')),
            ],
        ),
    ]
