# Generated by Django 4.0.4 on 2022-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmcro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Open'), (2, 'In Progress'), (3, 'Finished')], default=0),
        ),
    ]
