# Generated by Django 4.0.4 on 2022-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmcro', '0003_roomhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A name piece', max_length=255)),
            ],
        ),
    ]
