# Generated by Django 4.0.4 on 2022-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmcro', '0004_namepiece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namepiece',
            name='name',
            field=models.CharField(default='A name piece', max_length=255, unique=True),
        ),
    ]
