# Generated by Django 4.0.4 on 2022-05-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmcro', '0005_alter_namepiece_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NamePiece',
        ),
        migrations.AddField(
            model_name='member',
            name='editor',
            field=models.BooleanField(default=False),
        ),
    ]
