# Generated by Django 4.0.4 on 2022-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmcro', '0006_delete_namepiece_member_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
