version:  '3.7'

services:
 
  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test

  python:
    build:
      context: python
      dockerfile: ./Dockerfile
    volumes:
      - './..:/src'
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 
    restart: on-failure
    user: 8000:8000