version:  '3.7'

services:
 
  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test
    ports: 
      - "3307:3306"

  python:
    build:
      context: python
      dockerfile: ./Dockerfile
    volumes:
      - './..:/src'
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 
    restart: on-failure
    ports:
      - "8000:8000"
  
  redis:
    image: redis:7
    command: redis-server
    restart: always
    ports:
      - "6379:6379"